In [5]:
%pip install pandas

Collecting pandas
  Using cached pandas-2.2.3-cp313-cp313-macosx_11_0_arm64.whl.metadata (89 kB)
Requirement already satisfied: numpy>=1.26.0 in /opt/homebrew/lib/python3.13/site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/homebrew/Cellar/jupyterlab/4.4.0_1/libexec/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /opt/homebrew/Cellar/jupyterlab/4.4.0_1/libexec/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-2.2.3-cp313-cp313-macosx_11_0_arm64.whl (11.3 MB)
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, pandas
Successfully installed pandas-2.2.3 pytz-2025.2 tzdata-2025.2

[notice] A new release of pip is available: 25.0 -> 25.0.1
[notice] To update, run: /opt/homebrew/Cellar/jupyterlab/4.4.0_1/libexec/bin/python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [6]:
import pandas as pd

In [7]:
df = pd.read_csv("/Users/w620-admin/Desktop/nf-core/dataset/SEQC2_SV_high_conf/13059_2022_2816_MOESM4_ESM.tab", sep='\t')

In [27]:
df[1:20]

,SV_id,Chrom1,Pos1,Chrom2,Pos2,SV_Size_or_breakpoints_distance,SV_type,Replicates_called,Called by Pacbio,Called by Nanopore,Called by HiC,Called by Illumina,Called by 10X,strand1,strand2
1,chr1_964661_chr1_964780_+-,chr1,964661,chr1,964780,-112,DEL,2,1,1,0,0,0,+,-
2,chr1_1117831_chr22_20272153_++,chr1,1117831,chr22,20272153,0,TRA,57,1,1,0,1,1,+,+
3,chr1_1119512_chr22_20302979_++,chr1,1119512,chr22,20302979,0,TRA,43,1,1,0,1,1,+,+
4,chr1_1141429_chr1_1141430_+-,chr1,1141429,chr1,1141488,59,INS,2,1,1,0,0,0,+,-
5,chr1_1192665_chr1_1192666_+-,chr1,1192665,chr1,1192759,94,INS,2,1,1,0,0,0,+,-
6,chr1_1605511_chr1_1605595_++,chr1,1605511,chr1,1605595,-72,DEL,2,1,1,0,0,0,+,+
7,chr1_1979465_chr1_1979466_+-,chr1,1979465,chr1,1979744,279,INS,2,1,1,0,0,0,+,-
8,chr1_3299693_chr1_3300302_++,chr1,3299693,chr1,3300302,-670,DEL,2,1,1,0,0,0,+,+
9,chr1_8502130_chr1_8502130_+-,chr1,8502130,chr1,8502216,87,INS,2,1,1,0,0,0,+,-
10,chr1_9357666_chr1_9377061_+-,chr1,9357666,chr1,9377061,-19398,DEL,37,1,1,0,1,0,+,-
11,chr1_9495567_chr1_36665592_-+,chr1,9495567,chr1,36665592,27169806,DUP,47,1,1,1,1,1,-,+
12,chr1_11522794_chr1_11522794_+-,chr1,11522794,chr1,11523406,613,INS,3,1,1,0,0,0,+,-
13,chr1_13239707_chr1_13239707_+-,chr1,13239707,chr1,13239758,52,INS,2,1,1,0,0,0,+,-
14,chr1_18604738_chr1_18604795_++,chr1,18604738,chr1,18604795,-56,DEL,2,1,1,0,0,0,+,+
15,chr1_18825345_chr1_18825619_++,chr1,18825345,chr1,18825619,-274,DEL,3,1,1,0,0,0,+,+
16,chr1_18926035_chr1_18926035_+-,chr1,18926035,chr1,18926602,568,INS,3,1,1,0,0,0,+,-
17,chr1_20623754_chr1_20623754_+-,chr1,20623754,chr1,20624972,1219,INS,2,1,1,0,0,0,+,-
18,chr1_22416023_chr1_22416181_+-,chr1,22416023,chr1,22416181,-157,DEL,37,1,1,0,1,0,+,-
19,chr1_22826964_chr1_22827019_+-,chr1,22826964,chr1,22827019,-56,DEL,4,0,1,0,1,0,+,-

In [8]:
df[['strand1', 'strand2']] = df['SV_id'].str.extract(r'_(\+|-)(\+|-)')

In [9]:
df

,SV_id,Chrom1,Pos1,Chrom2,Pos2,SV_Size_or_breakpoints_distance,SV_type,Replicates_called,Called by Pacbio,Called by Nanopore,Called by HiC,Called by Illumina,Called by 10X,strand1,strand2
0,chr1_669501_chr1_669502_+-,chr1,669501,chr1,669502,75,INS,2,1,1,0,0,0,+,-
1,chr1_964661_chr1_964780_+-,chr1,964661,chr1,964780,-112,DEL,2,1,1,0,0,0,+,-
2,chr1_1117831_chr22_20272153_++,chr1,1117831,chr22,20272153,0,TRA,57,1,1,0,1,1,+,+
3,chr1_1119512_chr22_20302979_++,chr1,1119512,chr22,20302979,0,TRA,43,1,1,0,1,1,+,+
4,chr1_1141429_chr1_1141430_+-,chr1,1141429,chr1,1141430,59,INS,2,1,1,0,0,0,+,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1783,chr9_137342183_chr9_137342184_+-,chr9,137342183,chr9,137342184,76,INS,2,1,1,0,0,0,+,-
1784,chr9_137379350_chr9_137379350_+-,chr9,137379350,chr9,137379350,300,INS,2,1,1,0,0,0,+,-
1785,chr9_137716429_chr9_137716430_+-,chr9,137716429,chr9,137716430,786,INS,2,1,1,0,0,0,+,-
1786,chr9_137818759_chr9_137819193_+-,chr9,137818759,chr9,137819193,-464,DEL,2,1,1,0,0,0,+,-
1787,chr9_138069330_chr9_138069383_+-,chr9,138069330,chr9,138069383,-53,DEL,14,1,1,0,1,0,+,-

In [10]:
# Ensure SV_Size_or_breakpoints_distance is numeric

# Add the score to start2 for INS rows
df['Pos2'] = df.apply(
    lambda row: row['Pos2'] + row['SV_Size_or_breakpoints_distance'] - 1 if row['SV_type'] == 'INS' else row['Pos2'], 
    axis=1
)

In [11]:
df

,SV_id,Chrom1,Pos1,Chrom2,Pos2,SV_Size_or_breakpoints_distance,SV_type,Replicates_called,Called by Pacbio,Called by Nanopore,Called by HiC,Called by Illumina,Called by 10X,strand1,strand2
0,chr1_669501_chr1_669502_+-,chr1,669501,chr1,669576,75,INS,2,1,1,0,0,0,+,-
1,chr1_964661_chr1_964780_+-,chr1,964661,chr1,964780,-112,DEL,2,1,1,0,0,0,+,-
2,chr1_1117831_chr22_20272153_++,chr1,1117831,chr22,20272153,0,TRA,57,1,1,0,1,1,+,+
3,chr1_1119512_chr22_20302979_++,chr1,1119512,chr22,20302979,0,TRA,43,1,1,0,1,1,+,+
4,chr1_1141429_chr1_1141430_+-,chr1,1141429,chr1,1141488,59,INS,2,1,1,0,0,0,+,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1783,chr9_137342183_chr9_137342184_+-,chr9,137342183,chr9,137342259,76,INS,2,1,1,0,0,0,+,-
1784,chr9_137379350_chr9_137379350_+-,chr9,137379350,chr9,137379649,300,INS,2,1,1,0,0,0,+,-
1785,chr9_137716429_chr9_137716430_+-,chr9,137716429,chr9,137717215,786,INS,2,1,1,0,0,0,+,-
1786,chr9_137818759_chr9_137819193_+-,chr9,137818759,chr9,137819193,-464,DEL,2,1,1,0,0,0,+,-
1787,chr9_138069330_chr9_138069383_+-,chr9,138069330,chr9,138069383,-53,DEL,14,1,1,0,1,0,+,-

In [12]:
# Map the DataFrame columns to BEDPE fields
bedpe_df = pd.DataFrame({
    'chrom1': df['Chrom1'],
    'start1': df['Pos1'],  # BED format is 0-based
    'end1': -1,
    'chrom2': df['Chrom2'],
    'start2': df['Pos2'],  # BED format is 0-based
    'end2': -1,
    'name': df['SV_type'],
    'score': df['Replicates_called'],
    'strand1': df['strand1'],
    'strand2': df['strand2'],
    'id': df['SV_id'],
    'SV_Size_or_breakpoints_distance': df['SV_Size_or_breakpoints_distance'],
})

In [19]:
bedpe_df[1:10]

,chrom1,start1,end1,chrom2,start2,end2,name,score,strand1,strand2,id,SV_Size_or_breakpoints_distance
1,chr1,964661,-1,chr1,964780,-1,DEL,2,+,-,chr1_964661_chr1_964780_+-,-112
2,chr1,1117831,-1,chr22,20272153,-1,TRA,57,+,+,chr1_1117831_chr22_20272153_++,0
3,chr1,1119512,-1,chr22,20302979,-1,TRA,43,+,+,chr1_1119512_chr22_20302979_++,0
4,chr1,1141429,-1,chr1,1141488,-1,INS,2,+,-,chr1_1141429_chr1_1141430_+-,59
5,chr1,1192665,-1,chr1,1192759,-1,INS,2,+,-,chr1_1192665_chr1_1192666_+-,94
6,chr1,1605511,-1,chr1,1605595,-1,DEL,2,+,+,chr1_1605511_chr1_1605595_++,-72
7,chr1,1979465,-1,chr1,1979744,-1,INS,2,+,-,chr1_1979465_chr1_1979466_+-,279
8,chr1,3299693,-1,chr1,3300302,-1,DEL,2,+,+,chr1_3299693_chr1_3300302_++,-670
9,chr1,8502130,-1,chr1,8502216,-1,INS,2,+,-,chr1_8502130_chr1_8502130_+-,87

In [20]:
bedpe_df.to_csv("/Users/w620-admin/Desktop/nf-core/dataset/SEQC2_SV_high_conf/13059_2022_2816_MOESM4_ESM.bedpe", sep='\t', header=False, index=False, quoting=None)

In [16]:
import pysam
import pandas as pd

In [17]:


def bedpe_to_vcf(df, vcf_file, reference_genome):

    # Create a VCF file with pysam
    with pysam.VariantFile(vcf_file, 'w', header=create_vcf_header(reference_genome)) as vcf_out:
        for index, row in df.iterrows():
            # Create VCF record for each BEDPE entry
            vcf_record = create_vcf_record(row, vcf_out.header)
            vcf_out.write(vcf_record)

def create_vcf_header(reference_genome):
    header = pysam.VariantHeader()
    header.add_line("##fileformat=VCFv4.2")
    header.add_line(f"##reference={reference_genome}")
    header.add_line("##INFO=<ID=SVTYPE,Number=1,Type=String,Description=\"Type of structural variant\">")
    header.add_line("##INFO=<ID=SVLEN,Number=1,Type=Integer,Description=\"Length of structural variant\">")
    header.add_line("##INFO=<ID=END,Number=1,Type=Integer,Description=\"End position of the variant\">")
    header.add_line("##INFO=<ID=STRANDS,Number=1,Type=String,Description=\"Strand orientation of the variant\">")
    header.add_line("##INFO=<ID=REPLICATES,Number=1,Type=Integer,Description=\"Number of replicates called\">")
    header.add_sample("SAMPLE")

    return header

def create_vcf_record(row, header):
    chrom = row['Chrom1']
    pos = int(row['Pos1'])
    id = row['SV_id']
    ref = 'N'
    alt = f"<{row['SV_type']}>"
    qual = '.'
    filter = 'PASS'

    if row[['SV_type']] == "INS":
        end = int(row['Pos1']) + 1
    elif row[['SV_type']] == "DEL":
        end = int(row['Pos1']) + int(row['SV_Size_or_breakpoints_distance'])
    elif row[['SV_type']] == "DUP":
        end = int(row['Pos1']) + 1
    elif row[['SV_type']] == "TRA":
    
    info = {
        'SVTYPE': row['SV_type'],
        'SVLEN': row['SV_Size_or_breakpoints_distance'],
        'END': row['Pos2'],
        'STRANDS': row['SV_id'].split('_')[-1],
        'REPLICATES': row['Replicates_called']
    }

    record = header.new_record(
        contig=chrom,
        start=pos,
        id=id,
        alleles=(ref, alt),
        qual=qual,
        filter=filter,
        info=info
    )

    return record

SyntaxError: invalid syntax (1698139931.py, line 33)

In [106]:
# Example usage
bedpe_file = '/Users/w620-admin/Desktop/high_conf_sv/high_conf_sv.tab'
vcf_file = 'output.vcf'
reference_genome = '/Users/w620-admin/Desktop/high_conf_sv/hg38.fa'

bedpe_to_vcf(bedpe_file, vcf_file, reference_genome)

ValueError: Invalid chromosome/contig

In [25]:
import csv

input_file = "/Users/w620-admin/Desktop/nf-core/dataset/SEQC2_SV_high_conf/13059_2022_2816_MOESM4_ESM.bedpe"
output_file = "/Users/w620-admin/Desktop/nf-core/dataset/SEQC2_SV_high_conf/13059_2022_2816_MOESM4_ESM.sv_transformed.vcf"

vcf_header = """##fileformat=VCFv4.2
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structural variant">
##INFO=<ID=END,Number=1,Type=Integer,Description="End position of the variant">
##INFO=<ID=SVLEN,Number=1,Type=Integer,Description="Length of structural variant">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE
"""

with open(input_file, "r") as infile, open(output_file, "w") as outfile:
    outfile.write(vcf_header)
    reader = csv.DictReader(infile, delimiter="\t")

    for row in reader:
        chrom1 = row['chrom1']
        start1 = int(row['start1'])
        chrom2 = row['chrom2']
        start2 = int(row['start2'])
        svtype = row['name']
        id_ = row['id']
        strand1 = row['strand1']
        strand2 = row['strand2']
        svlen = row['SV_Size_or_breakpoints_distance']

        ref = "N"
        qual = "."
        fltr = "PASS"
        fmt = "GT"
        sample = "1/1"

        if svtype in ["DEL", "DUP"]:
            end = start2
            info = f"SVTYPE={svtype};END={end};SVLEN={svlen}"
            alt = f"<{svtype}>"
        elif svtype == "INS":
            end = start1 + 1
            info = f"SVTYPE=INS;END={end};SVLEN={svlen}"
            alt = "<INS>"
        elif svtype == "TRA":
            # Breakend ALT formatting depending on strand orientation
            if strand1 == "+" and strand2 == "+":
                alt = f"N[{chrom2}:{start2}["
            elif strand1 == "+" and strand2 == "-":
                alt = f"N]{chrom2}:{start2}]"
            elif strand1 == "-" and strand2 == "+":
                alt = f"]{chrom2}:{start2}]N"
            elif strand1 == "-" and strand2 == "-":
                alt = f"[{chrom2}:{start2}[N"
            info = f"SVTYPE=BND"
        else:
            continue  # skip unknown SV types

        vcf_line = f"{chrom1}\t{start1}\t{id_}\t{ref}\t{alt}\t{qual}\t{fltr}\t{info}\t{fmt}\t{sample}\n"
        outfile.write(vcf_line)

print(f"✔ VCF successfully written to {output_file}")

KeyError: 'chrom1'